"""create products table

Revision ID: dc22508a8f70
Revises: 
Create Date: 2026-02-13 17:03:47.443232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc22508a8f70'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('sku', sa.String(), nullable=False, comment='SAQ product SKU'),
    sa.Column('url', sa.String(), nullable=True, comment='SAQ product page URL'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='When first scraped'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='When last updated'),
    sa.Column('name', sa.String(), nullable=True, comment='Product name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Product description'),
    sa.Column('category', sa.String(), nullable=True, comment='Product category'),
    sa.Column('country', sa.String(), nullable=True, comment='Country of origin'),
    sa.Column('barcode', sa.String(), nullable=True, comment='GTIN-12 barcode'),
    sa.Column('color', sa.String(), nullable=True, comment='Wine color (red/white/rosé)'),
    sa.Column('size', sa.String(), nullable=True, comment='Bottle size (e.g., 750ml)'),
    sa.Column('image', sa.String(), nullable=True, comment='Product image URL'),
    sa.Column('price', sa.Float(), nullable=True, comment='Price in CAD'),
    sa.Column('currency', sa.String(), nullable=True, comment='Currency code (CAD)'),
    sa.Column('availability', sa.Boolean(), nullable=True, comment='In stock?'),
    sa.Column('manufacturer', sa.String(), nullable=True, comment='Manufacturer name'),
    sa.Column('rating', sa.Float(), nullable=True, comment='Aggregate rating (0-5)'),
    sa.Column('review_count', sa.Integer(), nullable=True, comment='Number of reviews'),
    sa.Column('region', sa.String(), nullable=True, comment='Wine region'),
    sa.Column('appellation', sa.String(), nullable=True, comment="Appellation d'origine"),
    sa.Column('designation', sa.String(), nullable=True, comment='Désignation réglementée'),
    sa.Column('classification', sa.String(), nullable=True, comment='Wine classification'),
    sa.Column('grape', sa.String(), nullable=True, comment='Grape variety (cépage)'),
    sa.Column('alcohol', sa.String(), nullable=True, comment='Alcohol content (e.g., 13.5%)'),
    sa.Column('sugar', sa.String(), nullable=True, comment='Sugar content'),
    sa.Column('producer', sa.String(), nullable=True, comment='Producer name'),
    sa.Column('saq_code', sa.String(), nullable=True, comment='Code SAQ (internal)'),
    sa.Column('cup_code', sa.String(), nullable=True, comment='Code CUP (UPC)'),
    sa.PrimaryKeyConstraint('sku')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
