"""oauth_accounts table and email display_name on users

Revision ID: 079ed4c8b997
Revises: c2e04e28cb5f
Create Date: 2026-04-03 17:21:51.951898

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "079ed4c8b997"
down_revision: str | Sequence[str] | None = "c2e04e28cb5f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Truncate users before adding NOT NULL email column.
    # Cascades to: chat_sessions/messages, tasting_notes, watches, user_store_preferences.
    # Safe: only one user row exists (the admin), who will re-register via OAuth.
    op.execute("TRUNCATE users CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth_accounts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="Owning user"),
        sa.Column(
            "provider",
            sa.String(length=20),
            nullable=False,
            comment="OAuth provider: github or google",
        ),
        sa.Column(
            "provider_user_id",
            sa.String(),
            nullable=False,
            comment="Provider's stable user identifier",
        ),
        sa.Column(
            "email",
            sa.String(length=254),
            nullable=False,
            comment="Email from provider at time of linking (may differ from users.email)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When this provider account was linked",
        ),
        sa.CheckConstraint("provider IN ('github', 'google')", name="ck_oauth_accounts_provider"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "provider_user_id", name="uq_oauth_accounts_provider_uid"),
    )
    op.create_index(op.f("ix_oauth_accounts_user_id"), "oauth_accounts", ["user_id"], unique=False)
    op.add_column(
        "users",
        sa.Column(
            "email",
            sa.String(length=254),
            nullable=False,
            comment="Primary email from OAuth provider (lowercased)",
        ),
    )
    op.add_column(
        "users",
        sa.Column("display_name", sa.String(), nullable=True, comment="User-set display name"),
    )
    op.alter_column(
        "users",
        "telegram_id",
        existing_type=sa.BIGINT(),
        nullable=True,
        comment="Telegram user ID — notification channel only, not an auth credential",
        existing_comment="Telegram user ID (64-bit)",
    )
    op.drop_column("users", "first_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "first_name",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment="Telegram first name",
        ),
    )
    op.alter_column(
        "users",
        "telegram_id",
        existing_type=sa.BIGINT(),
        nullable=False,
        comment="Telegram user ID (64-bit)",
        existing_comment="Telegram user ID — notification channel only, not an auth credential",
    )
    op.drop_column("users", "display_name")
    op.drop_column("users", "email")
    op.drop_index(op.f("ix_oauth_accounts_user_id"), table_name="oauth_accounts")
    op.drop_table("oauth_accounts")
    # ### end Alembic commands ###
