"""add watches table

Revision ID: 417779ce6a81
Revises: b5c67feb72f8
Create Date: 2026-02-19 13:24:03.562577

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "417779ce6a81"
down_revision: str | Sequence[str] | None = "b5c67feb72f8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "watches",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "user_id",
            sa.String(),
            nullable=False,
            comment="Channel-prefixed user ID (e.g. tg:123456)",
        ),
        sa.Column("sku", sa.String(), nullable=False, comment="Watched product SKU"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When watch was created",
        ),
        sa.ForeignKeyConstraint(
            ["sku"],
            ["products.sku"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "sku", name="uq_watches_user_sku"),
    )
    op.create_index(op.f("ix_watches_sku"), "watches", ["sku"], unique=False)
    op.create_index(op.f("ix_watches_user_id"), "watches", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_watches_user_id"), table_name="watches")
    op.drop_index(op.f("ix_watches_sku"), table_name="watches")
    op.drop_table("watches")
    # ### end Alembic commands ###
