"""add cascade delete on chat_sessions.user_id FK

Revision ID: 71be3d37f1fc
Revises: 079ed4c8b997
Create Date: 2026-04-05 01:05:25.155435

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "71be3d37f1fc"
down_revision: str | Sequence[str] | None = "079ed4c8b997"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("chat_sessions_user_id_fkey"), "chat_sessions", type_="foreignkey")
    op.create_foreign_key(None, "chat_sessions", "users", ["user_id"], ["id"], ondelete="CASCADE")
    op.create_unique_constraint(None, "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "chat_sessions", type_="foreignkey")
    op.create_foreign_key(
        op.f("chat_sessions_user_id_fkey"), "chat_sessions", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
