"""add product_availability table

Revision ID: a1551e61f3e6
Revises: ac8698d47eee
Create Date: 2026-02-28 16:42:38.780517

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1551e61f3e6"
down_revision: str | Sequence[str] | None = "ac8698d47eee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_availability",
        sa.Column("sku", sa.String(), nullable=False, comment="Watched product SKU"),
        sa.Column(
            "online_available",
            sa.Boolean(),
            nullable=True,
            comment="Online availability from GraphQL stock_status (NULL = not yet checked)",
        ),
        sa.Column(
            "store_qty",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment='Store stock map: {"23009": 44, "23132": 12}',
        ),
        sa.Column(
            "checked_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When availability was last checked",
        ),
        sa.ForeignKeyConstraint(
            ["sku"],
            ["products.sku"],
        ),
        sa.PrimaryKeyConstraint("sku"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_availability")
    # ### end Alembic commands ###
