"""phase 6 schema: add wine attrs, rename availability, drop columns and table

Revision ID: a1665520b1d7
Revises: e864f62c1048
Create Date: 2026-03-04 22:23:05.915466

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1665520b1d7"
down_revision: str | Sequence[str] | None = "e864f62c1048"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_availability")
    # Rename preserves existing data (Alembic auto-generated drop+add, manually fixed)
    op.alter_column(
        "products",
        "availability",
        new_column_name="online_availability",
        comment="Available online?",
    )
    op.add_column(
        "products",
        sa.Column(
            "pastille_gout",
            sa.String(),
            nullable=True,
            comment="SAQ taste profile (e.g. 'Aromatique et souple')",
        ),
    )
    op.add_column(
        "products",
        sa.Column("vintage", sa.String(), nullable=True, comment="Millésime (e.g. '2023')"),
    )
    op.add_column(
        "products",
        sa.Column(
            "tasting_profile",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="portrait_* attributes from Adobe",
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "cepage_adobe",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment='Structured blend: [{"code":"MALB","pct":96},{"code":"SYRA","pct":4}]',
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "store_availability",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment='Store IDs carrying this product: ["23002","23004",...]',
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "attribute_hash",
            sa.String(),
            nullable=True,
            comment="Hash of embedding-relevant fields for change detection",
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "embedded_hash",
            sa.String(),
            nullable=True,
            comment="Hash at time of last embedding — embed when != attribute_hash",
        ),
    )
    op.create_index(
        "ix_products_store_availability_gin",
        "products",
        ["store_availability"],
        unique=False,
        postgresql_using="gin",
    )
    op.drop_column("products", "barcode")
    op.drop_column("products", "color")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "color",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
            comment="Wine color (red/white/rosé)",
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "barcode", sa.VARCHAR(), autoincrement=False, nullable=True, comment="GTIN-12 barcode"
        ),
    )
    op.drop_index(
        "ix_products_store_availability_gin", table_name="products", postgresql_using="gin"
    )
    op.drop_column("products", "embedded_hash")
    op.drop_column("products", "attribute_hash")
    op.drop_column("products", "store_availability")
    op.drop_column("products", "cepage_adobe")
    op.drop_column("products", "tasting_profile")
    op.drop_column("products", "vintage")
    op.drop_column("products", "pastille_gout")
    op.alter_column(
        "products",
        "online_availability",
        new_column_name="availability",
        comment="In stock?",
    )
    op.create_table(
        "product_availability",
        sa.Column(
            "sku", sa.VARCHAR(), autoincrement=False, nullable=False, comment="Watched product SKU"
        ),
        sa.Column(
            "online_available",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
            comment="Online availability from GraphQL stock_status (NULL = not yet checked)",
        ),
        sa.Column(
            "store_qty",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
            comment='Store stock map: {"23009": 44, "23132": 12}',
        ),
        sa.Column(
            "checked_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
            comment="When availability was last checked",
        ),
        sa.ForeignKeyConstraint(
            ["sku"], ["products.sku"], name=op.f("product_availability_sku_fkey")
        ),
        sa.PrimaryKeyConstraint("sku", name=op.f("product_availability_pkey")),
    )
    # ### end Alembic commands ###
