"""add user_store_preferences table and saq_store_id to stock_events

Revision ID: ac8698d47eee
Revises: e2b8b4081934
Create Date: 2026-02-27 11:50:13.654224

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac8698d47eee"
down_revision: str | Sequence[str] | None = "e2b8b4081934"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_store_preferences",
        sa.Column(
            "user_id",
            sa.String(),
            nullable=False,
            comment="Channel-prefixed user ID (e.g. tg:123456)",
        ),
        sa.Column(
            "saq_store_id", sa.String(), nullable=False, comment="Preferred store identifier"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When preference was saved",
        ),
        sa.ForeignKeyConstraint(
            ["saq_store_id"],
            ["stores.saq_store_id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "saq_store_id"),
    )
    op.add_column(
        "stock_events",
        sa.Column(
            "saq_store_id",
            sa.String(),
            nullable=True,
            comment="Store where change was detected (NULL = online)",
        ),
    )
    op.create_index(
        op.f("ix_stock_events_saq_store_id"), "stock_events", ["saq_store_id"], unique=False
    )
    op.create_foreign_key(None, "stock_events", "stores", ["saq_store_id"], ["saq_store_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "stock_events", type_="foreignkey")
    op.drop_index(op.f("ix_stock_events_saq_store_id"), table_name="stock_events")
    op.drop_column("stock_events", "saq_store_id")
    op.drop_table("user_store_preferences")
    # ### end Alembic commands ###
