"""embed hash columns rename

Revision ID: aeebb2d09f16
Revises: 203969d8fd14
Create Date: 2026-03-07 14:54:49.057442

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aeebb2d09f16"
down_revision: str | Sequence[str] | None = "203969d8fd14"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "embedding_input_hash",
            sa.String(),
            nullable=True,
            comment="Hash of embedding-relevant fields for change detection",
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "last_embedded_hash",
            sa.String(),
            nullable=True,
            comment="embedding_input_hash at time of last --embed-sync run",
        ),
    )
    op.drop_column("products", "attribute_hash")
    op.drop_column("products", "embedded_hash")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "embedded_hash",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
            comment="Hash at time of last embedding — embed when != attribute_hash",
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "attribute_hash",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
            comment="Hash of embedding-relevant fields for change detection",
        ),
    )
    op.drop_column("products", "last_embedded_hash")
    op.drop_column("products", "embedding_input_hash")
    # ### end Alembic commands ###
