"""add restock_events table

Revision ID: b0bfe635f0c3
Revises: 417779ce6a81
Create Date: 2026-02-19 15:36:56.644672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0bfe635f0c3'
down_revision: Union[str, Sequence[str], None] = '417779ce6a81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restock_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(), nullable=False, comment='Product that changed availability'),
    sa.Column('available', sa.Boolean(), nullable=False, comment='New availability state (True=restock, False=destock)'),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False, comment='When the change was detected'),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True, comment='When notifications were sent (NULL=pending)'),
    sa.ForeignKeyConstraint(['sku'], ['products.sku'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restock_events_processed_at'), 'restock_events', ['processed_at'], unique=False)
    op.create_index(op.f('ix_restock_events_sku'), 'restock_events', ['sku'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restock_events_sku'), table_name='restock_events')
    op.drop_index(op.f('ix_restock_events_processed_at'), table_name='restock_events')
    op.drop_table('restock_events')
    # ### end Alembic commands ###
