"""add locale to users

Revision ID: d54ff3a506b5
Revises: 71be3d37f1fc
Create Date: 2026-04-06 15:04:41.282938

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d54ff3a506b5"
down_revision: str | Sequence[str] | None = "71be3d37f1fc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "locale",
            sa.String(length=5),
            nullable=True,
            comment="Preferred UI locale (fr, en) — NULL = use browser default",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "locale")
    # ### end Alembic commands ###
