"""add recommendation_logs table

Revision ID: de3eafa552b5
Revises: 77f251efc3bc
Create Date: 2026-03-09 12:22:53.500124

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de3eafa552b5"
down_revision: str | Sequence[str] | None = "77f251efc3bc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recommendation_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "user_id",
            sa.String(),
            nullable=True,
            comment="Channel-prefixed user ID (e.g. tg:123456)",
        ),
        sa.Column("query", sa.Text(), nullable=False, comment="Raw user input"),
        sa.Column(
            "parsed_intent",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Structured intent from Claude",
        ),
        sa.Column(
            "returned_skus",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Ordered list of recommended SKUs",
        ),
        sa.Column(
            "product_count", sa.Integer(), nullable=False, comment="Number of results returned"
        ),
        sa.Column(
            "latency_ms",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Per-stage timing breakdown",
        ),
        sa.Column(
            "feedback", sa.String(), nullable=True, comment="User feedback: positive or negative"
        ),
        sa.Column("error", sa.Text(), nullable=True, comment="Error type if pipeline failed"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When the recommendation was requested",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recommendation_logs_created_at"),
        "recommendation_logs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommendation_logs_user_id"), "recommendation_logs", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recommendation_logs_user_id"), table_name="recommendation_logs")
    op.drop_index(op.f("ix_recommendation_logs_created_at"), table_name="recommendation_logs")
    op.drop_table("recommendation_logs")
    # ### end Alembic commands ###
