"""add store model

Revision ID: e2b8b4081934
Revises: 205be03e8a95
Create Date: 2026-02-26 16:26:50.263733

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e2b8b4081934"
down_revision: str | Sequence[str] | None = "205be03e8a95"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stores",
        sa.Column(
            "saq_store_id",
            sa.String(),
            nullable=False,
            comment="SAQ store identifier (API 'identifier' field)",
        ),
        sa.Column("name", sa.String(), nullable=False, comment="Store display name"),
        sa.Column(
            "store_type",
            sa.String(),
            nullable=True,
            comment="SAQ, SAQ Sélection, SAQ Express, SAQ Dépôt, etc.",
        ),
        sa.Column("address", sa.String(), nullable=True, comment="Street address (address1)"),
        sa.Column("city", sa.String(), nullable=False, comment="City"),
        sa.Column("postcode", sa.String(), nullable=True, comment="Postal code"),
        sa.Column("telephone", sa.String(), nullable=True, comment="Phone number"),
        sa.Column("latitude", sa.Float(), nullable=True, comment="GPS latitude"),
        sa.Column("longitude", sa.Float(), nullable=True, comment="GPS longitude"),
        sa.Column(
            "temporarily_closed", sa.Boolean(), nullable=False, comment="Temporarily closed flag"
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, comment="When first scraped"
        ),
        sa.PrimaryKeyConstraint("saq_store_id"),
    )
    op.create_index(op.f("ix_stores_city"), "stores", ["city"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stores_city"), table_name="stores")
    op.drop_table("stores")
    # ### end Alembic commands ###
