"""drop saq_code cup_code currency from products

Revision ID: e864f62c1048
Revises: a1551e61f3e6
Create Date: 2026-03-02 19:11:12.662495

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e864f62c1048"
down_revision: str | Sequence[str] | None = "a1551e61f3e6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "currency")
    op.drop_column("products", "saq_code")
    op.drop_column("products", "cup_code")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "cup_code", sa.VARCHAR(), autoincrement=False, nullable=True, comment="Code CUP (UPC)"
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "saq_code",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
            comment="Code SAQ (internal)",
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "currency",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
            comment="Currency code (CAD)",
        ),
    )
    # ### end Alembic commands ###
